apps/customers/urls.py
from django.urls import include, path
from rest_framework import routers

from . import views


app_name = 'customers'

router = routers.DefaultRouter()
router.register('address', views.ShippingAddressView)
router.register('cards', views.CardView, basename='cards')

urlpatterns = [
	path('', include(router.urls)),
	path('stripe/', views.StripeView.as_view())
] 

core/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),

    path('catalog/', include('catalog.urls')),
    path('customers/', include('customers.urls')),
    path('store/', include('store.urls')),
]

apps/address/models.py
from django.db import models
from django_countries.fields import CountryField


class AbstractAddress(models.Model):
	line1 = models.CharField(max_length=30)
	line2 = models.CharField(max_length=30, blank=True, null=True)
	city = models.CharField(max_length=30)
	state = models.CharField(max_length=30)
	zipcode = models.CharField(max_length=20)
	country = CountryField(multiple=False)

	class Meta:
		abstract = True

	def __str__(self):
		line2 = " " + self.line2 if self.line2 else ""
		return f"{self.line1}{line2}, {self.city}, {self.state}, {self.zipcode}, {self.country}"

apps/customers/models.py
from django.apps import apps
from django.db import models
from django.db.models.signals import post_delete, post_save
from django.dispatch import receiver
from django.utils import timezone

from address.models import AbstractAddress


# Models
class Customer(models.Model):
	PURCHASE_WAIT_TIME = 5

	user = models.OneToOneField('users.User', related_name='customer', on_delete=models.CASCADE)
	if apps.is_installed('store'):
		price_level = models.ForeignKey('store.PriceLevel', on_delete=models.SET_NULL, blank=True, null=True)
		payment_methods = models.ManyToManyField('store.PaymentMethod', blank=True)

	stripe_customer_id = models.CharField("Customer Stripe ID", max_length=100, blank=True, null=True)
	purchase_attempt_time = models.DateTimeField(default=timezone.now)
	admin_made = models.BooleanField(default=False)

	class Meta:
		verbose_name = 'Customer Info'

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		if apps.is_installed('store'):
			self.old_price_level = self.price_level

	def __str__(self):
		return str(self.user)
		

class CustomerAddress(AbstractAddress):
	first_name = models.CharField("First Name", max_length=30)
	last_name = models.CharField("Last Name", max_length=30)
	email = models.EmailField("Email Address", max_length=30)


class Card(CustomerAddress):
	user = models.ForeignKey('users.User', related_name='card', on_delete=models.CASCADE)
	src_id = models.CharField("Credit Card Stripe ID", max_length=30)

	class Meta(CustomerAddress.Meta):
		verbose_name = "Credit Card"


class ShippingAddress(CustomerAddress):
	user = models.ForeignKey('users.User', related_name='shipping_address', on_delete=models.CASCADE)

	class Meta(CustomerAddress.Meta):
		verbose_name = "Shipping Address"


# Signals
@receiver(post_save, sender='users.User', dispatch_uid="user_created")
def user_created(sender, instance, created, *args, **kwargs):
	customer = Customer.objects.get_or_create(user=instance)[0]


@receiver(post_delete, sender=Customer, dispatch_uid="delete_customer")
def delete_customer(sender, instance, *args, **kwargs):
	if instance.user:
		instance.user.delete()

apps/customers/views.py
from django.conf import settings
from django.shortcuts import redirect
from django.views.generic import TemplateView
from rest_framework.response import Response
from rest_framework.viewsets import ModelViewSet

from .models import Card, ShippingAddress
from .serializers import CardSerializer, ShippingAddressSerializer
from .utils import stripe_get_card, stripe_delete_card


# Used to send Stripe Token to API
class StripeView(TemplateView):
	template_name = 'customers/stripe.html'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['pub_key'] = settings.STRIPE_PUBLISHABLE_KEY
		return context

	def post(self, *args, **kwargs):
		return redirect(self.request.path_info)


class CardView(ModelViewSet):
	queryset = Card.objects.all()
	serializer_class = CardSerializer
	http_method_names = ['get', 'post', 'patch', 'delete']

	def get_queryset(self):
		return self.queryset.filter(user=self.request.user)

	def retrieve(self, request, *args, **kwargs):
		instance = self.get_object()
		card = stripe_get_card(instance)
		return Response(card)

	def perform_destroy(self, instance):
		stripe_delete_card(instance)
		return super().perform_destroy(instance)


class ShippingAddressView(ModelViewSet):
	queryset = ShippingAddress.objects.all()
	serializer_class = ShippingAddressSerializer
	http_method_names = ['get', 'post', 'patch', 'delete']

	def get_queryset(self):
		return self.queryset.filter(user=self.request.user)

apps/customers/templates/customers/stripe.html
{% load static %}


<script src="https://js.stripe.com/v3/"></script>
<span id="pub-key" hidden>{{ pub_key }}</span>
<span id="url" hidden>{% url 'customers:cards-list' %}</span>


<form id="stripe-form" method="POST" style="max-width:400; margin:100px;">
	{% csrf_token %}

	<label for="id_line1">Line 1</label>
	<input type="text" name='line1'>
	<br>

	<label for="id_line2">Line 2 (optional)</label>
	<input type="text" name='line2'>
	<br>

	<label for="id_city">City</label>
	<input type="text" name='city'>
	<br>


	<label for="id_state">State</label>
	<input type="text" name='state'>
	<br>

	<label for="id_zipcode">Zip Code</label>
	<input type="text" name='zipcode'>
	<br>

	<label for="id_country">Country</label>
	<input type="text" name='country'>
	<br>

	<label for="id_first_name">First Name</label>
	<input type="text" name='first_name'>
	<br>

	<label for="id_last_name">Last Name</label>
	<input type="text" name='last_name'>
	<br>

	<label for="id_email">Email Address</label>
	<input type="email" name='email'>
	<br>



	<h3>Payment</h3>
	<label for="card-element">Credit or debit card</label>
	<div id="card-element">
	</div>
	<div id="card-errors" role="alert"></div>

	<button type="submit"></button>
</form>


<script type="text/javascript" src="{% static 'customers/js/stripe.js' %}"></script>